[[redirects]]
from = "/_next/static/*"
to = "/.netlify/functions/next/_next/static/:splat"
status = 200
force = true


[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
